//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bloque()
        {
            this.BloqueCompetencia = new HashSet<BloqueCompetencia>();
        }
    
        public long IdBloque { get; set; }
        public string Titulo { get; set; }
        public byte Parcial { get; set; }
        public double Porcentaje { get; set; }
        public string Grupos { get; set; }
        public string nombre_materia { get; set; }
        public string Pre_competencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloqueCompetencia> BloqueCompetencia { get; set; }
    }
}
