//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloqueCompetencia
    {
        public long IdBloqueCompetencia { get; set; }
        public long IdBloque { get; set; }
        public string Descripcion { get; set; }
        public int Numero { get; set; }
    
        public virtual Bloque Bloque { get; set; }
    }
}
