//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenidos_a_Evaluar
    {
        public int IdBloque { get; set; }
        public string Titulo { get; set; }
        public Nullable<float> Porcentaje { get; set; }
        public Nullable<int> Parcial { get; set; }
    }
}
