//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plani_por_parcial
    {
        public int Id_planificacion { get; set; }
        public string Comp_Ger { get; set; }
        public string Comp_Dici { get; set; }
        public string Conflicto { get; set; }
        public string Situacion { get; set; }
        public int Parcial { get; set; }
        public string nombre_materia { get; set; }
        public string Posicion_list { get; set; }
    }
}
