//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bloque> Bloque { get; set; }
        public virtual DbSet<BloqueCompetencia> BloqueCompetencia { get; set; }
        public virtual DbSet<Contenidos_a_Evaluar> Contenidos_a_Evaluar { get; set; }
        public virtual DbSet<Materia_t> Materia_t { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Plani_por_parcial> Plani_por_parcial { get; set; }
        public virtual DbSet<Datos_Plantel> Datos_Plantel { get; set; }
        public virtual DbSet<Actividad_Didactica> Actividad_Didactica { get; set; }
        public virtual DbSet<Secuencia_Didactica> Secuencia_Didactica { get; set; }
    }
}
